### ISSUE TITLE
Meaning of 4d and 6b

### ISSUE THREAD

**Issue by Bergmann97** [Rudolchr/Adopets#1]
Could you please more specify, what you meant with 4. "d) shelter should be able to retrieve the list to verify the data" and 6. "b) shelter should be able to retrieve the list to verify it"?
We are not entirely sure what you exactly meant.

**Comment by Rudolchr** [comment]
The shelter should like a non logged in visitor of the app be able to retrieve and view the lists "found home" and "looking for home", while a shelter additionally should be able to update the animals on the list that the shelter is providing.
