### ISSUE TITLE
Pets' date of birth

### ISSUE THREAD

**Issue by achillease** [Rudolchr/Adopets#3]
I'd recommend to provide the birthdate of pets as a full `Date` instead of just `month` and `year` though its important for pet owners to know the exact date (for celebration). Additionally there it's also  important to ensure that the adoption will not be done before the pet has had professional care within the first days / weeks and is not adopted too early.

**Comment by puchala-mag** [comment]
The idea of the month/year birth date was to take into account the pets, which were found and so their birth date isn't known and can only be estimated. However you can programm it as a full Date. If the date of birth is known, it would be written there, if not, the shelter will just make some day up.
You don't have to take into account that the adoption shouldn't take place too soon -- we assume, that the shelter puts online only advertisements of these pets, which are ready for an adopiton.

**Comment by achillease** [comment]
okay thank you
