### ISSUE TITLE
Advert - pet adoption

### ISSUE THREAD

**Issue by achillease** [Rudolchr/Adopets#4]
I'm a litte confused. I your documentation you wrote the following:
- Shelters can add pets to their list
- Shelters can delete ***adverts*** which eventually move the pets to the adoption list
- Shelters can remove pets from the adoption list which returns them to their pets list

Assuming that there is a difference between ***Adverts*** an the plain pets list, you are missing:
- create adverts for listed pets
- move pets from the pets list to the adoption list (which may had no advert to delete)

Otherwise (more likely) you did just mean "pets list entry" instead of ***advertisement***. Then the task list is complete and there is just a lack of accuracy in your ubiquitous language. Therefore is will open another issue

**Comment by puchala-mag** [comment]
Sorry for the confusion -- you are right, there is just a lack of accuracy in our ubiquitous language. 
In this case advert/advertisement/pet is the same thing. "Pets" was just a mental shortcut -- you obviously don't create a physical pet, but just an advert about one. All these words refere to the Object Pet (add an Object Pet to the looking for home list, delete an Object Pet from looking for home list, remove an Object Pet from the adopted list etc.).

**Comment by achillease** [comment]
okay. thanks for the clarification
