### ISSUE TITLE
Ubiquitous language

### ISSUE THREAD

**Issue by achillease** [Rudolchr/Adopets#5]
To make development easier, I would suggest that we agree on a more precise and meaningful language. Environments like "looking for home" and "found home" are not precise enough for us.

Both represent lists of pets, that have to be described (internally) in a clearer way (besides what it will be labeled later). My suggestion would be:
- "looking for home" => shelter list / pets list
- "found home" => adoption list / adopted list

---

there is also the unclarity mentioned in #4 that has to be clarified. The word "advertisement" shows up indifferently.

Though the pets are inside lists i'd suggest (internally) to just call them entries (in one of the mentioned lists).

**Comment by puchala-mag** [comment]
What about:
"looking for home" => pets for adoption,
"found home" => adopted (or adopted pets)?

**Comment by achillease** [comment]
I intended to avoid using the same terms for different meanings. "Pets for adoption" and "adopted pets" has the correct meaning, but in speech it is very similar

**Comment by puchala-mag** [comment]
Then what about "Our pets" and "Adopted"? I would avoid using a word "list", it sounds as if it would objectify the animals.

**Comment by achillease** [comment]
Oh I think we are misunderstanding. The names "looking for home" and "found home" shall be used for the presentational side of the application though this empathises with the idea of giving pets a "home". There is absolutely nothing wrong about it.

I was speaking about our internally used language (the ubiquitous one) to ensure that we (the owners and devs) are communicating on the same level of understanding. This should be done to minimize the gap between the requirements and the  product you will be served. This will save dev and communication time.

Btw.: In my opinion calling pets "advertisements" sounds a little objectifying ^^

**Comment by puchala-mag** [comment]
Okay, now I see, what you was asking about. 
For our internal communication are pets list and adopted list totally fine.
