### ISSUE TITLE
Use Case diagram

### ISSUE THREAD

**Issue by achillease** [Rudolchr/Adopets#6]
I just created a Use-Case-Diagram from the given tasks. This will serve as a base for further diagrams as well a the development phase:

![Adopets_usecase](https://user-images.githubusercontent.com/62384153/122933700-288b9900-d36f-11eb-8bcc-9f086e938554.png)

I'd like to know if that diagram represents the use-cases correctly, to ensure we have the same understanding of the requirements.

**Comment by Rudolchr** [comment]
Yes the diagram looks good.
