### ISSUE TITLE
Lists of additional  information

### ISSUE THREAD

**Issue by achillease** [Rudolchr/Adopets#7]
To clarify the further development we need additional lists of information:
- What `species` will be availible for `pets`?
- What are possible values `vaccination status` (or will this be filled manually as a text)?

**Comment by Rudolchr** [comment]
> What species will be availible for pets?

There will be dogs, cats and birds

> What are possible values vaccination status (or will this be filled manually as a text)?

You can implement this as a manual text input.

**Comment by achillease** [comment]
okay thanks
